name: Test PR

on:
  pull_request:
    branches:
      - main

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "ðŸŽ‰ The test PR Action."
      - name: ðŸ›Ž Checkout
        uses: actions/checkout@v2
      # - name: Fail
      #   run: exit 1
      - name: Always do something
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: TestUpload
          path: Test
